<template>
  <n-card :title="$t('brand.colorDemo.title')" class="color-theme-demo">
    <template #header-extra>
      <n-select
        v-model:value="selectedSkinColor"
        :placeholder="$t('brand.colorDemo.selectSkinColor')"
        :options="skinColorOptions"
        style="width: 240px"
        @update:value="handleColorChange"
      >
        <template #render-label="{ option }">
          <div class="flex items-center gap-2">
            <div class="color-preview-mini">
              <div
                class="color-dot"
                :style="{ backgroundColor: getPrimaryColor(option.value) }"
              />
            </div>
            <span>{{ option.label }}</span>
          </div>
        </template>
      </n-select>
    </template>

    <div v-if="currentPalette" class="demo-content">
      <div class="color-palette-section">
        <h4>{{ $t('brand.colorDemo.autoGeneratedPalette') }}</h4>
        <div class="color-palette-grid">
          <div class="color-item primary">
            <div
              class="color-block"
              :style="{ backgroundColor: currentPalette.primary }"
            >
              <div class="color-overlay">
                <span class="color-type">{{ $t('brand.colorDemo.primaryColor') }}</span>
                <span class="color-value">{{ currentPalette.primary }}</span>
              </div>
            </div>
          </div>
          <div class="color-item secondary">
            <div
              class="color-block"
              :style="{ backgroundColor: currentPalette.secondary }"
            >
              <div class="color-overlay">
                <span class="color-type">{{ $t('brand.colorDemo.secondaryColor') }}</span>
                <span class="color-value">{{ currentPalette.secondary }}</span>
              </div>
            </div>
          </div>
          <div class="color-item accent">
            <div
              class="color-block"
              :style="{ backgroundColor: currentPalette.accent }"
            >
              <div class="color-overlay">
                <span class="color-type">{{ $t('brand.colorDemo.accentColor') }}</span>
                <span class="color-value">{{ currentPalette.accent }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="theme-demo-section">
        <h4>{{ $t('brand.colorDemo.themeApplicationDemo') }}</h4>
        <div class="demo-components">
          <div class="demo-group">
            <label>{{ $t('brand.colorDemo.buttonComponent') }}</label>
            <div class="button-demo">
              <button
                class="demo-button primary"
                :style="{
                  backgroundColor: currentPalette.primary,
                  borderColor: currentPalette.primary,
                }"
              >
                {{ $t('brand.colorDemo.primaryButton') }}
              </button>
              <button
                class="demo-button secondary"
                :style="{
                  backgroundColor: currentPalette.secondary,
                  borderColor: currentPalette.secondary,
                }"
              >
                {{ $t('brand.colorDemo.secondaryButton') }}
              </button>
              <button
                class="demo-button accent"
                :style="{
                  backgroundColor: currentPalette.accent,
                  borderColor: currentPalette.accent,
                }"
              >
                {{ $t('brand.colorDemo.accentButton') }}
              </button>
            </div>
          </div>

          <div class="demo-group">
            <label>{{ $t('brand.colorDemo.cardComponent') }}</label>
            <div class="card-demo">
              <div
                class="demo-card"
                :style="{ borderTopColor: currentPalette.primary }"
              >
                <div
                  class="card-header"
                  :style="{ color: currentPalette.primary }"
                >
                  {{ $t('brand.colorDemo.mainContentCard') }}
                </div>
                <div class="card-content">{{ $t('brand.colorDemo.cardSampleText') }}</div>
              </div>
            </div>
          </div>

          <div class="demo-group">
            <label>{{ $t('brand.colorDemo.badgeComponent') }}</label>
            <div class="badge-demo">
              <span
                class="demo-badge primary"
                :style="{ backgroundColor: currentPalette.primary }"
              >
                {{ $t('brand.colorDemo.primaryBadge') }}
              </span>
              <span
                class="demo-badge secondary"
                :style="{ backgroundColor: currentPalette.secondary }"
              >
                {{ $t('brand.colorDemo.secondaryBadge') }}
              </span>
              <span
                class="demo-badge accent"
                :style="{ backgroundColor: currentPalette.accent }"
              >
                {{ $t('brand.colorDemo.accentBadge') }}
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="css-classes-section">
        <h4>{{ $t('brand.colorDemo.generatedCssClasses') }}</h4>
        <div class="css-code">
          <pre><code>{{ generateCSSExample() }}</code></pre>
        </div>
      </div>
    </div>

    <div v-else class="empty-state">
      <n-empty :description="$t('brand.colorDemo.selectSkinColorHint')" />
    </div>
  </n-card>
</template>

<script setup lang="ts">
import { $t } from '@vben/locales';

import { ref } from 'vue';
import { NCard, NSelect, NEmpty } from 'naive-ui';
import {
  useColorTheme,
  useSkinColorOptions,
} from '../../../composables/useColorTheme';
import {
  getPrimaryColorById,
  getColorPaletteById,
} from '../../../utils/colorUtils';

const { skinColorOptions } = useSkinColorOptions();

const selectedSkinColor = ref<string>('');
const currentPalette = ref<ReturnType<typeof getColorPaletteById> | null>(null);

const getPrimaryColor = (skinColorId: string) => {
  return getPrimaryColorById(skinColorId);
};

const handleColorChange = (skinColorId: string) => {
  if (skinColorId) {
    currentPalette.value = getColorPaletteById(skinColorId);
  } else {
    currentPalette.value = null;
  }
};

const generateCSSExample = () => {
  if (!currentPalette.value) return '';

  const p = currentPalette.value;
  return `/* ${$t('brand.colorDemo.cssAutoTheme')} */
bg-[${p.primary}]   /* ${$t('brand.colorDemo.cssPrimaryBg')} */
bg-[${p.secondary}] /* ${$t('brand.colorDemo.cssSecondaryBg')} */
bg-[${p.accent}]    /* ${$t('brand.colorDemo.cssAccentBg')} */

text-[${p.primary}]   /* ${$t('brand.colorDemo.cssPrimaryText')} */
text-[${p.secondary}] /* ${$t('brand.colorDemo.cssSecondaryText')} */
text-[${p.accent}]    /* ${$t('brand.colorDemo.cssAccentText')} */

border-[${p.primary}]   /* ${$t('brand.colorDemo.cssPrimaryBorder')} */
border-[${p.secondary}] /* ${$t('brand.colorDemo.cssSecondaryBorder')} */
border-[${p.accent}]    /* ${$t('brand.colorDemo.cssAccentBorder')} */`;
};
</script>

<style scoped>
.color-theme-demo {
  margin-bottom: 24px;
}

.demo-content {
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.color-palette-section h4 {
  margin-bottom: 16px;
  font-size: 16px;
  font-weight: 600;
}

.color-palette-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
}

.color-item {
  text-align: center;
}

.color-block {
  position: relative;
  height: 120px;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: transform 0.2s ease;
}

.color-block:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.color-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  color: white;
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.color-type {
  font-weight: 600;
  font-size: 14px;
}

.color-value {
  font-family: monospace;
  font-size: 12px;
  opacity: 0.9;
}

.theme-demo-section h4 {
  margin-bottom: 16px;
  font-size: 16px;
  font-weight: 600;
}

.demo-components {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.demo-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.demo-group label {
  font-weight: 500;
  color: #666;
}

.button-demo {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
}

.demo-button {
  padding: 8px 16px;
  border: 1px solid;
  border-radius: 6px;
  color: white;
  font-weight: 500;
  cursor: pointer;
  transition: opacity 0.2s ease;
}

.demo-button:hover {
  opacity: 0.9;
}

.demo-card {
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  border-top-width: 3px;
  overflow: hidden;
}

.card-header {
  padding: 12px 16px;
  font-weight: 600;
  border-bottom: 1px solid #e5e7eb;
}

.card-content {
  padding: 16px;
  color: #666;
}

.badge-demo {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.demo-badge {
  padding: 4px 8px;
  border-radius: 4px;
  color: white;
  font-size: 12px;
  font-weight: 500;
}

.css-classes-section h4 {
  margin-bottom: 16px;
  font-size: 16px;
  font-weight: 600;
}

.css-code {
  background: #f8f9fa;
  border: 1px solid #e9ecef;
  border-radius: 6px;
  padding: 16px;
}

.css-code pre {
  margin: 0;
  font-size: 12px;
  line-height: 1.5;
  color: #495057;
}

.color-preview-mini {
  display: flex;
  align-items: center;
}

.color-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  border: 1px solid rgba(0, 0, 0, 0.2);
}

.flex {
  display: flex;
}

.items-center {
  align-items: center;
}

.gap-2 {
  gap: 0.5rem;
}

.empty-state {
  text-align: center;
  padding: 48px 0;
}
</style>
